<?php
    Class Armi{
        public array $listaArmi=[
            'Ascia'=>6,
            'BastoneFerrato'=>6,
            'Falcetto'=>4,
            'Giavellotto'=>6,
            'Lancia'=>6,
            'MartelloLeggero'=>4,
            'Mazza'=>6,
            'Pugnale'=>4,
            'Randello'=>4,
            'RandelloPesante'=>8,
            'ArcoCorto'=>6,
            'BalestraLeggera'=>8,
            'Dardo'=>4,
            'Fionda'=>4,
            'Alabarda'=>10,
            'AsciaBipenne'=>12,
            'AsciaDaBattaglia'=>8,
            'Falcione'=>10,
            'Frusta'=>4,
            'LanciaDaCavaliere'=>12,
            'Maglio'=>'2d6',
            'MartelloDaGuerra'=>8,
            'Mazzafrusto'=>8,
            'MorningStar'=>8,
            'Picca'=>10,
            'PicconeDaGuerra'=>8,
            'Scimitarra'=>6,
            'SpadaCorta'=>6,
            'SpadaLunga'=>8,
            'Spadone'=>'2d6',
            'Stocco'=>8,
            'Tridente'=>6,
            'ArcoLungo'=>8,
            'BalestraAMano'=>6,
            'BalestraPesante'=>10,
        ]; 
   
    
    }