<?php
    Class Armi{
        public array $listaArmi=[
            'mani' => 4,
            'ascia'=>6,
            'bastone ferrato'=>6,
            'falcetto'=>4,
            'giavellotto'=>6,
            'lancia'=>6,
            'martello leggero'=>4,
            'mazza'=>6,
            'pugnale'=>4,
            'randello'=>4,
            'randello pesante'=>8,
            'arco corto'=>6,
            'balestra leggera'=>8,
            'dardo'=>4,
            'fionda'=>4,
            'alabarda'=>10,
            'ascia bipenne'=>12,
            'ascia da battaglia'=>8,
            'Falcione'=>10,
            'Frusta'=>4,
            'LanciaDaCavaliere'=>12,
            'Maglio'=>'2d6',
            'MartelloDaGuerra'=>8,
            'Mazzafrusto'=>8,
            'MorningStar'=>8,
            'Picca'=>10,
            'PicconeDaGuerra'=>8,
            'Scimitarra'=>6,
            'SpadaCorta'=>6,
            'spada lunga'=>8,
            'Spadone'=>'2d6',
            'Stocco'=>8,
            'Tridente'=>6,
            'ArcoLungo'=>8,
            'BalestraAMano'=>6,
            'BalestraPesante'=>10,
        ]; 
   
    
    }